### ISSUE TITLE
Unchecking Tweet / Share boxes not respected on draft save

### ISSUE THREAD

**Issue by pippinsplugins** [cklosowski/post-promoter-pro#122]
If you create a new post and uncheck the boxes to tweet / share the post when published and then click `Save Draft`, the boxes are re-checked when the page is reloaded.

Note: this assumes the defaults is to have the boxes checked.

**Comment by pippinsplugins** [comment]
Oh, no, it's actually not quite that. Turns out if you have the defaults set to `Checked` and then publish a post with the boxes unchecked, the tweet / share goes out anyway.

**Comment by cklosowski** [comment]
Is this only on the 'Share on publish boxes'?

**Comment by pippinsplugins** [comment]
Yes
