### ISSUE TITLE
Scheduled shares recreated upon update if previously deleted

### ISSUE THREAD

**Issue by pippinsplugins** [cklosowski/post-promoter-pro#19]
1. Publish a post and setup the schedule for the shares
2. Go to the Schedule page and delete some of the scheduled shares
3. Go back to the post and click Update (as though you fixed a typo)
4. Go back to the Schedule page and you'll see the previously-deleted shares are now rescheduled

**Comment by cklosowski** [comment]
@pippinsplugins If you haven't seen this again yet I'm going to close it out. With 2.2 rolled out and the share system completely rewritten I think we're good here. Reopen if necessary.

**Comment by pippinsplugins** [comment]
I haven't seen it happen again either.
