### ISSUE TITLE
Schedule not always created 

### ISSUE THREAD

**Issue by pippinsplugins** [cklosowski/post-promoter-pro#21]
I don't know exactly how to reliably replicate, but the custom share text is definitely not always respected.

I just published a [post](https://pippinsplugins.com/shortcodes-101-good-bad-use-cases-shortcodes/) and I setup custom shares to happen on day 2 and 3. Day 2 was left with the default {post_title} and day 3 was given a custom message.

The metabox looks like this (before and after publish):
![image](https://cloud.githubusercontent.com/assets/1034109/4837271/1fe868bc-5fd3-11e4-8a42-bd970ba3efbe.png)

But there is no scheduled shares:
![image](https://cloud.githubusercontent.com/assets/1034109/4837273/27cbdc80-5fd3-11e4-8565-5f3dc9a0e914.png)

**Comment by cklosowski** [comment]
@pippinsplugins with 2.2 and the new share system, i'm going to close this out as it hasn't been reported again. Re-open if necessary.

**Comment by pippinsplugins** [comment]
:+1:

I have not seen this happen again.
