### ISSUE TITLE
Uncaught Reference Error

### ISSUE THREAD

**Issue by pippinsplugins** [cklosowski/post-promoter-pro#74]
I got a message saying that my Facebook authentication was about to expire so I went to refresh it.

After revoking access, I am unable to re-connect. There's a JS error:
```
Uncaught ReferenceError: _ is not defined
https://pippinsplugins.com/wp-admin/admin.php?page=ppp-social-settings line 212
```

**Comment by pippinsplugins** [comment]
Nevermind, that error comes from Jetpack: https://github.com/Automattic/jetpack/issues/1851

**Comment by cklosowski** [comment]
Will keep this open for now, want to make sure it goes away after Jetpack pushes their fix.

**Comment by cklosowski** [comment]
Closing this as it's not been seen again yet. We'll re-open if necessary
