### ISSUE TITLE
Warn in metabox when something is already scheduled

### ISSUE THREAD

**Issue by cklosowski** [cklosowski/post-promoter-pro#79]
From Jennifer Bourn again (awesome feedback) that we should find a way to warn in the post meta box when a user is trying to schedule a Tweet at the same time as one already scheduled.

Either we can eliminate that time from being selected, or highlight the date/time fields in red when it's already assigned.

**Comment by pippinsplugins** [comment]
:+1:

**Comment by cklosowski** [comment]
The current functionality only works on rows added after the edit post page is loaded.
