### ISSUE TITLE
Twitter character count should account for attached images.

### ISSUE THREAD

**Issue by cklosowski** [cklosowski/post-promoter-pro#86]
Currently the twitter counter only accounts for a link being attached and warns 23 characters shorter than 140. If someone attaches an image, the count should warn earlier as it accounts for another 23 characters. (46 in total with Image and link)

**Comment by pippinsplugins** [comment]
I suspect this is what caused one of my recent posts to not get tweeted.
With the image the tweet was too long.

**Comment by cklosowski** [comment]
Yeah it's likely to be the cause. At this point it only warns you when you are nearing/at the limit with the link (140 - 23), when the attached image is detected it should knock that down another 23 and give the RED count at 94 characters.
